### ISSUE TITLE
Storage: Data references

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/open-data-service#21]
Instead of passing the actual data to the transformation service, the scheduler should pass a reference to the data. The transformation service should then fetch the data, transform it and pass a reference to the transformed data as a result. We need to decide whether the transformation needs an own persistence to save its results or if we want to use some kind of a shared solution.

**Comment by dirkriehle** [comment]
Why? Is this for performance optimization? Better than, we maintain value semantics, even if we pass references around mabye using copy-on-write semantics (effectively simulating value objects). But I'm not sure I'm arguing on the right level here. In general, we first need to see whether we should use an existing library!

**Comment by mathiaszinnen** [comment]
Yes, it is for performance optimization. And I would agree that normally, we should focus on functionality before optimizing performance (if this is what you are implying). 
In this case, however, I think it is crucial. What we are doing now is so inefficient, that it makes the ODS unusable for real scenarios with a considerable amount of data: 
Currently, the data flow is external data source -> adapter service -> scheduler -> transformation service -> scheduler -> storage/API service. In each of these steps, the whole data has to be transferred via the (internal) network, persisted and loaded to the main memory. 
Both are very expensive operations, which makes importing the data via the ods many times than just importing it directly. 
To fix this problem I was trying to gradually transform this passing of the data itself to a reference passing: We persist it once in the adapter service and with a reference to the data instead of loading it again for each step. This is the context of this issue. Is that what you mean by copy-on-write semantics?

**Comment by mathiaszinnen** [comment]
Closing the issue for now since we are focussing on core removal first
